# site title
title: Story of Linkgo

# github user
user: linkgo

# issue repo
repo: linkgo.github.io

# multi-author
authors: librae8226, roybein, twolun, zhaozhongyao

# per page
per_page: 10

#sandbox
sandbox: false
